// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXMXeT1i1edB4rAPt7ym1mKf0fYHnZ44',
    appId: '1:1008688867428:web:d6911fea724e812b8c5771',
    messagingSenderId: '1008688867428',
    projectId: 'app-qlkth-nhom8',
    authDomain: 'app-qlkth-nhom8.firebaseapp.com',
    storageBucket: 'app-qlkth-nhom8.firebasestorage.app',
    measurementId: 'G-HQKBFZ7JLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI9kfUtLOoEDytuneaOKoIPR59AbC5GGQ',
    appId: '1:1008688867428:android:0c2e69ff1fd170878c5771',
    messagingSenderId: '1008688867428',
    projectId: 'app-qlkth-nhom8',
    storageBucket: 'app-qlkth-nhom8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUfGMED2RN3vKYe7bZCsm7ZPTIpwiGRQ',
    appId: '1:1008688867428:ios:80f3da074a34a02e8c5771',
    messagingSenderId: '1008688867428',
    projectId: 'app-qlkth-nhom8',
    storageBucket: 'app-qlkth-nhom8.firebasestorage.app',
    iosBundleId: 'com.example.appQlkthNhom8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUfGMED2RN3vKYe7bZCsm7ZPTIpwiGRQ',
    appId: '1:1008688867428:ios:80f3da074a34a02e8c5771',
    messagingSenderId: '1008688867428',
    projectId: 'app-qlkth-nhom8',
    storageBucket: 'app-qlkth-nhom8.firebasestorage.app',
    iosBundleId: 'com.example.appQlkthNhom8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrXMXeT1i1edB4rAPt7ym1mKf0fYHnZ44',
    appId: '1:1008688867428:web:c1c863bf1b5366f38c5771',
    messagingSenderId: '1008688867428',
    projectId: 'app-qlkth-nhom8',
    authDomain: 'app-qlkth-nhom8.firebaseapp.com',
    storageBucket: 'app-qlkth-nhom8.firebasestorage.app',
    measurementId: 'G-B2JPZLQXNM',
  );
}
